In [ ]:
import pandas as pd

url = r'SINASC_2026.csv'
df = pd.read_csv(url, sep=';')

df.head()

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
nulos = df.isna().sum()
print(nulos[nulos > 0].to_markdown)

In [ ]:
for coluna in df.columns:
    if df[coluna].isna().any():
        print(f"------ coluna: {coluna} ------")
        print(df[coluna].value_counts(dropna=False))
        print("\n""-----------------""\n")

In [ ]:
colunas_categoricas = [
    "ORIGEM", "LOCNASC", "ESCMAE", "GESTACAO", "GRAVIDEZ", 
    "PARTO", "CONSULTAS", "SEXO", "RACACOR", "IDANOMAL", 
    "ESCMAE2010", "RACACORMAE", "TPMETESTIM", "TPAPRESENT", 
    "STTRABPART", "STCESPARTO", "TPNASCASSI", "TPFUNCRESP", 
    "TPDOCRESP", "ESCMAEAGR1", "STDNEPIDEM", "STDNNOVA", "PARIDADE"
]

for coluna in colunas_categoricas:
    if coluna in df.columns and df[coluna].isna().any():
        print(f"------ coluna: {coluna} ------")
        print(df[coluna].unique())
        print("\n-----------------\n")

TPDOCRESP, TPMETESTIM tem valores invalidos
STTRABPART um valor nunca eh escolhidos

In [87]:
print(f'valores coluna origem: {df["ORIGEM"].unique()}')
print(f'valores coluna codigo pais de residencia (CODPAISRES): {df["CODPAISRES"].unique()}')
print(f'valores coluna versao do sistema: {df["VERSAOSIST"].unique()}')

df.head()

valores coluna origem: [1]
valores coluna codigo pais de residencia (CODPAISRES): [ 1. nan]
valores coluna versao do sistema: <ArrowStringArray>
['3.2.50', '3.2.01', '2.2.03', nan, '3.2.00', '3.2.02']
Length: 6, dtype: str

,contador,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,...,TPFUNCRESP,TPDOCRESP,DTDECLARAC,ESCMAEAGR1,STDNEPIDEM,STDNNOVA,CODPAISRES,TPROBSON,PARIDADE,KOTELCHUCK
0,1,1,2494299.0,110002,1,22.0,2.0,4.0,999992.0,0.0,...,2.0,3.0,8032026.0,6.0,1.0,1,1.0,1,0,5
1,2,1,2515520.0,110002,1,33.0,2.0,5.0,223405.0,1.0,...,2.0,3.0,20032026.0,8.0,1.0,1,1.0,5,1,5
2,3,1,2515520.0,110002,1,25.0,1.0,4.0,354125.0,0.0,...,2.0,3.0,20032026.0,6.0,1.0,1,1.0,1,0,5
3,4,1,2515504.0,110002,1,36.0,1.0,4.0,514120.0,2.0,...,5.0,5.0,20032026.0,6.0,1.0,1,1.0,5,1,5
4,5,1,2515504.0,110002,1,38.0,2.0,4.0,516205.0,2.0,...,5.0,5.0,20032026.0,6.0,1.0,1,1.0,4,1,5

In [89]:
df.drop(columns=["ORIGEM", "CODPAISRES", "ESCMAE2010", "ESCMAEAGR1", "VERSAOSIST", "NUMEROLOTE", "DTRECEBIM", "APGAR1", "APGAR5"], inplace=True)
df.head()

,contador,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,STCESPARTO,TPNASCASSI,TPFUNCRESP,TPDOCRESP,DTDECLARAC,STDNEPIDEM,STDNNOVA,TPROBSON,PARIDADE,KOTELCHUCK
0,1,2494299.0,110002,1,22.0,2.0,4.0,999992.0,0.0,0.0,...,3.0,1.0,2.0,3.0,8032026.0,1.0,1,1,0,5
1,2,2515520.0,110002,1,33.0,2.0,5.0,223405.0,1.0,0.0,...,1.0,1.0,2.0,3.0,20032026.0,1.0,1,5,1,5
2,3,2515520.0,110002,1,25.0,1.0,4.0,354125.0,0.0,0.0,...,3.0,1.0,2.0,3.0,20032026.0,1.0,1,1,0,5
3,4,2515504.0,110002,1,36.0,1.0,4.0,514120.0,2.0,0.0,...,1.0,1.0,5.0,5.0,20032026.0,1.0,1,5,1,5
4,5,2515504.0,110002,1,38.0,2.0,4.0,516205.0,2.0,2.0,...,1.0,1.0,5.0,5.0,20032026.0,1.0,1,4,1,5